# Generated by Django 4.2.7 on 2023-11-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('raw_image', models.ImageField(upload_to='raw/')),
                ('processed_image', models.ImageField(blank=True, null=True, upload_to='processed/')),
                ('success_capture', models.BooleanField(default=False)),
                ('success_detection', models.BooleanField(default=False)),
                ('detection_count', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
