# Generated by Django 4.2.7 on 2023-11-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagerecord',
            name='image_path_quoted',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='imagerecord',
            name='processed_name',
            field=models.CharField(default='Processed_Capture_15c88b4c-4de0-41ca-9ac6-f6cd35204648.jpg', max_length=255),
        ),
        migrations.AddField(
            model_name='imagerecord',
            name='raw_name',
            field=models.CharField(default='Capture_65bb9bba-0454-4bd7-93b2-88b2a4ca4760.jpg', max_length=255),
        ),
        migrations.AlterField(
            model_name='imagerecord',
            name='detection_count',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
